### ISSUE TITLE
config not found in your index.js  ISSUE 

### ISSUE THREAD

**Issue by msonowal** [isaacperaza/elixir-busting#2]
Kindly add this line to your package index.js
var config = Elixir.config;
I have added it in the PR
#3

**Comment by isaacperaza** [comment]
Done, thanks @msonowal.

**Comment by isaacperaza** [comment]
@msonowal I also updated the npm version package (1.0.3). Note: If you have a npm user please send it to me to add you as a elixir-busting collaborator.

**Comment by msonowal** [comment]
@isaacperaza 
https://www.npmjs.com/~msonowal
